config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  resources :books, only: [:show, :edit, :update, :index, :create, :destroy]  
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    validates :title, {presence: true}
    validates :body, {presence: true, length: {maximum: 200}}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, {length: {minimum: 2}}
  validates :introduction, {length: {maximum: 50}}

  
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_images.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  #未ログインユーザが「TOP、ABOUTを除く」ビューにアクセスすると、自動的にログインビューへ飛ぶdeviseのヘルパーメソッド
  before_action :configure_permitted_parameters, if: :devise_controller?
  #こうすることでdevise利用の機能（ユーザ登録、ログイン認証など）が使われる前にconfigure_permitted_parametersメソッドが実行されます。

 def after_sign_in_path_for(resource)
   user_path(resource)
 end
 
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @books = Book.all
    @book = Book.new
    @user = current_user
    @book1 = Book.find(params[:id])
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def edit
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "update successfully"
      redirect_to "/books/#{@book.id}"
    else
      render:edit
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "create successfully"
      redirect_to "/books/#{@book.id}"
    else
      @books = Book.all
      @user = current_user
      render:index
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:notice] = "destroy successfully"
      redirect_to "/books"
    end
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

aaaaa

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @users = User.all
    @book = Book.new
    @user = current_user
    @user1 = User.find(params[:id])
  end
  
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully"
      redirect_to "/users/#{@user.id}"
    else
      render:edit
    end
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
    
    @user = User.find(params[:id])
  end
  
  def nill
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <div>
    <h2>New book</h2>
    <%= form_with model: book,url: "/books", method: :post do |f| %>
   
    <div class="error-message">  
      <% if book.errors.any? %>
        <ul class="text-danger">
        <%= book.errors.count %> error has occurred
        </ul>
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>   

   
    <div class="books-text">
      <div class="title-box">
        <p>Title</p>
        <p>
          <%= f.text_field:title %>
        </p>
      </div>
      <div class="body-box">
        <p>Opinion</p>
        <p>
          <%= f.text_area:body %>
        </p>
      </div>
      <div class="btn-box" >
        <%= f.submit "Create Book", class:"btn btn-success" %>
      </div>
    </div>
    <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <div class="edit-title mt-3">
      <h1>Editing Book</h1>
    </div>
    
    <%= form_with model: @book do |f| %>
    <div class="books-text">
      
      <div class="error-message">  
        <% if @book.errors.any? %>
        <ul class="text-danger">
          <%= @book.errors.count %> error has occurred
        </ul>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
          </ul>
        <% end %>
      </div>
      
      <div class="title-box">
        <p>Title</p>
        <p>
          <%= f.text_field:title, class:"btn-block" %>
        </p>
      </div>
      <div class="body-box">
        <p>Opinion</p>
        <p>
          <%= f.text_area:body, class:"btn-block" %>
        </p>
      </div>
      <div class="btn-box">
        <%= f.submit "Update Book", class:"btn btn-success" %>
      </div>
    </div>
    <% end %>
    
    <div class="book-btn" >
      <%= link_to "Show",book_path(@book),class:"btn btn-info mt-3" %>
      <%= link_to "Back",books_path,class:"btn btn-info mt-3" %>
    </div>
  </div>

</div>
</div>
</div>

app/views/books/index.html.erb
<div>
  <% if flash[:notice] %>
  <div class="btn-block btn btn-success">
    <%= flash[:notice]%>
  </div>
  <% end %>
</div>

<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    
<div class="col-md-3">
  <h2>User info</h2>
  <div>
  <% if @user.profile_image.attached? %>
    <%= image_tag @user.profile_image, size: "100x100" %>
  <% else %>
    <%= image_tag 'no_images.jpg', size: "100x100" %>
  <% end %>
  </div>
  <table class="table">
    <tr>
      <th>name</th>
      <th><%= @user.name  %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
    </tr>
  </table>
  <div>
    <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
       <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<br></br>

   <%= render 'books/list', {user: @user,book: @book,user1: @user1,book1: @book1} %>
</div>
 
   <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
       <table class="table">
       <thead>
          <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
          </tr>
       </thead>

       <tbody>
       <% @books.each do |book| %>
       <tr>
         <td>
         <%= link_to user_path(book.user.id) do %>   
         　<%= image_tag book.user.get_profile_image(100,100) %>
         <% end %>
       　</td>
       　<td>
        　  <%= link_to book.title, book_path(book.id) %>
         </td>
         <td><%= book.body %></td>
       </tr>
      <% end %>
      </tbody>
      </table>
    </div>
</div>

app/views/books/show.html.erb
<div>
  <% if flash[:notice] %>
  <div class="btn-block btn btn-success">
    <%= flash[:notice]%>
  </div>
  <% end %>
</div>

<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    
<div class="col-md-3">
  <h2>User info</h2>
  <div>
  <% if @user.profile_image.attached? %>
    <%= image_tag @book1.user.profile_image, size: "100x100" %>
  <% else %>
    <%= image_tag 'no_images.jpg', size: "100x100" %>
  <% end %>
  </div>
  <table class="table">
    <tr>
      <th>name</th>
      <th><%= @book1.user.name  %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @book1.user.introduction %></th>
    </tr>
  </table>
  <div>
    <%= link_to edit_user_path(@book1.user), class:"btn btn-outline-secondary btn-block" do %>
       <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<br></br>

    <%= render 'books/list', {user: @user,book: @book,book1: @book1} %>
</div>
    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tr>
        <td>
        <%= link_to user_path(@book1.user.id) do %>
          <%= image_tag @book1.user.get_profile_image(100,100) %>
        <% end %>
        </td>
        <td><%= link_to @book1.title,book_path(@book1.id)   %></td>
        <td><%= @book1.body %></td>
        <% if @book1.user == current_user %>
          <td><%= link_to "Edit",edit_book_path(@book1.id),class:"btn btn-success" %></td>
        <% end %>
        <% if @book1.user == current_user %>
          <td><%= link_to "Destroy",book_path(@book1.id),class:"btn btn-danger",method: :delete,"data-confirm" => "本当に削除しますか？" %></td>
        <% end %>
      </tr>
    </table>
    <tr>
      <td><%= link_to @book1.user.name, user_path(@book1.user.id) %></td>
    </tr>
   </div>
</div>

app/views/homes/about.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
      <h1>Welcome to<span><i class="fas fa-book"></i></span>Bookers!!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div>
  <% if flash[:notice] %>
  <div class="btn-block btn btn-success">
    <%= flash[:notice]%>
  </div>
  <% end %>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to<span><i class="fas fa-book"></i></span>Bookers!!</h1>
      <p>In <span><i class="fas fa-book"></i></span><strong>Bookers,</strong></p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <div class="col btn btn-info btn-sm btn-block mb-3 ">
            <%= link_to "Log in", new_user_session_path, class:"text-white" %>
          </div>
        </div>
        <div class="row">
          <div class="col btn btn-success btn-sm btn-block " >
            <%= link_to "Sign up", new_user_registration_path, class:"text-white" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br></br>
  <header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container">
    <a class="navbar-brand" href="/"><span>Bookers</span></a>
    <div class="header-list">
    <ul class="navbar-nav ml-auto ">
    <% if user_signed_in? %>
      <li class="nav-link text-align ">
        <%= link_to user_path(current_user.id), class:"text-white" do %>
          <i class="fas fa-home"></i><span> Home</span>
        <% end %>
      </li>
      <li class="nav-link text-align">
        <%= link_to users_path, class:"text-white" do %>
          <i class="fas fa-users"></i><span> Users</span>
        <% end %>
      </li>
      <li class="nav-link text-align">
        <%= link_to books_path, class:"text-white" do %>
          <i class="fas fa-book-open"></i><span> Books</span>
        <% end %>
      </li>
      <li class="nav-link text-align">
        <%= link_to destroy_user_session_path, method: :delete, class:"text-white" do %>
          <i class="fas fa-sign-out-alt"></i><span> Log out</span>
        <% end %>
      </li>
    <% else %>
      <li class="nav-link text-align" >
        <%= link_to root_path , class:"text-white" do  %>
          <i class="fas fa-home"></i><span> Home</span>
        <% end %>
      </li>
      <li class="nav-link text-align">
        <%= link_to about_path , class:"text-white" do %>
          <i class="fas fa-link"></i><span> About</span>
        <% end %>
      </li>
      <li class="nav-link text-align">
        <%= link_to new_user_registration_path , class:"text-white" do %>
          <i class="fas fa-user-plus"></i><span> Sign up</span>
        <% end %>
      </li>
      <li class="nav-link text-align">
        <%= link_to new_user_session_path, class:"text-white" do %>
          <i class="fas fa-sign-in-alt"></i><span> Log in</span>
        <% end %>
      </li>
    <% end %>
    </ul>
    </div>
    </nav>
  </header>
  <main>
  <%= yield %>
  </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<div class="user-info mt-3">
  <h2>User info</h2>
</div>
<div>
 <%= form_with model: @user do |f| %>
 
     <div class="error-message">  
      <% if @user.errors.any? %>
      <ul class="text-danger">
        <%= @user.errors.count %> error has occurred
      </ul>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
        </ul>
      <% end %>
     </div>

 
  <label for="inputName">Name</label>
  <p><%= f.text_field :name, autofocus: true, id:"inputName", class:"btn-block" %></p>
  <label for="inputImage">Image</label>
  <p><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></p>  
  <p>introduction</p>
  <p><%= f.text_area :introduction, class:"btn-block" %></p>
  <p><%= f.submit "Update User", class:"btn btn-secondary" %></p>
 <% end %>
</div>

</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

<div class="col-md-3">
  <h2>User info</h2>
  <div>
  <% if @user.profile_image.attached? %>
    <%= image_tag @user.profile_image, size: "100x100" %>
  <% else %>
    <%= image_tag 'no_images.jpg', size: "100x100" %>
  <% end %>
  </div>
  <table class="table">
    <tr>
      <th>name</th>
      <th><%= @user.name  %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
    </tr>
  </table>
  <div>
    <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
       <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<br></br>

  <%= render 'books/list',{user: @user,user1: @user1,book: @book} %>
</div>
   <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
        <tr>
         <td><%= image_tag user.get_profile_image(100,100) %></td>
         <td><%= user.name %></td>
         <td><%= link_to "Show",user_path(user.id)%></td>
        </tr>
      <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <% if flash[:notice] %>
  <div class="btn-block btn btn-success">
    <%= flash[:notice]%>
  </div>
  <% end %>
</div>

<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    
<div class="col-md-3">
  <h2>User info</h2>
  <div>
  <% if @user.profile_image.attached? %>
    <%= image_tag @user1.profile_image, size: "100x100" %>
  <% else %>
    <%= image_tag 'no_images.jpg', size: "100x100" %>
  <% end %>
  </div>
  <table class="table">
    <tr>
      <th>name</th>
      <th><%= @user1.name  %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @user1.introduction %></th>
    </tr>
  </table>
  <div>
    <%= link_to edit_user_path(@user1), class:"btn btn-outline-secondary btn-block" do %>
       <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<br></br>
    
    <%= render 'books/list',{user: @user,book: @book,user1: @user1,book1: @book1} %>
</div>
      <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <% @user1.books.each do |book| %>
          <tr>
            <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body%></td>
          </tr>
        <% end %>
      </table>

      </div>
</div>